const SELECTORS = {
  TASK_DESCR: '.game__task-annotation',
  MENU: '.menu',
  MENU_CONTAINER: '.menu__menu-container',
  BURGER_MENU_BTN: '#burgerMenuBtn',
  CLOSE_MENU_BTN: '#closeMenuBtn',
  ANSWER_FIELD: '#answer',
  ENTER_BTN: '#EnterBtn',
  TABLE: '.game__table',
  HTML_SYNT_CODE_AREA: '#htmlCode',
  TOTAL_TASK_QTY_FIELD: '#totalLvls',
  CUR_LVL_FIELD: '#curLvl',
  MENU_ITEM_TEMPLATE: '#menuItemTemmplate',
  INC_TASK_BTN: '#incTaskBtn',
  DEC_TASK_BTN: '#decTaskBtn',
  TASK_STATUS_ICON: '#taskStatusCheck',
  TASK_DESC_FIELD: '.menu__text',
  RESET_BTN: '.menu__reset-btn',
  POPUP: '.popup',
  POPUP_BTN: '.popup__btn',
  POPUP_ACTIVE: 'popup_state_active',
  HELP_BTN: '.code__btn_type_help',
  MENU_ITEM_ELEMENT: '.menu__item',
  MENU_ITEM_ELEM_TITLE: '.menu__item-title',
  MENU_ITEM_ELEM_NUM: '.menu__item-num',
  MENU_ITEM_ELEM_ICON: 'img',
  DESIRED: '.desired',
  DESIRED_WRONG: 'desired_state_wrong',
  DESIRED_CORRECT: 'desired_state_correct',
  BLINK: 'code__input_style_blink',
  MENU_ITEM_CURRENT: 'menu__item_current',
  MENU_ACTIVE: 'menu_state_active',
};

export default SELECTORS;
